services:
    discord_db_handler:
        build: ./discord
        container_name: discord_db_handler
        ports:
            - "5020:5020"
        restart: unless-stopped
        environment:
            MYSQL_DISCORD_USER: ${MYSQL_DISCORD_USER}
            MYSQL_DISCORD_PASSWORD: ${MYSQL_DISCORD_PASSWORD}
            MYSQL_DISCORD_DATABASE: ${MYSQL_DISCORD_DATABASE}
            MYSQL_DISCORD_HOST: mariadb
            LD_LIBRARY_PATH: /usr/lib/mariadb
            PYTHONUNBUFFERED: 1

    mariadb:
        image: mariadb:latest
        container_name: mariadb_container
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./db_data:/var/lib/mysql